### ISSUE TITLE
Event-append rejections must not take the server down

### ISSUE THREAD

**Issue by mintopia** [mintopia/harmonic#371]
## What to build

The run-event append path is fire-and-forget on the hottest path in the runner. A racing task delete rejects the append and — with no rejection handler and no process-level unhandled-rejection logger — the rejection takes the whole server down.

Make append failures on this path non-fatal and legible, and give the process a safety net so any future fire-and-forget miss degrades to a logged event instead of a crash.

## Acceptance criteria

- [ ] A task deleted while its Run is appending events does not crash the server; the failure is logged and the Run settles normally
- [ ] An unhandled rejection anywhere in the server is logged as a legible error event (with Run/Task context where available) instead of being fatal
- [ ] Regression test reproduces the delete-during-append race and asserts survival

## Blocked by

None (can start immediately).

**Comment by mintopia** [comment]
Resolved by commit `9cca923` on branch `harmonic/task-371-run-1`.

**Root cause** — `driveOnce`'s run-event append (`src/execution/runner.ts`) was fire-and-forget with no `.catch()`. A racing task-delete cascade removes the `runs` row, the late `appendEvent` insert then violates the `run_events`→`runs` foreign key, and with no rejection handler nor a process-level `unhandledRejection` logger, that rejection crashed the whole server.

**Fix**
- Extracted the append into a guarded `recordRunEvent(runId, event)` that `.catch()`es. The benign racing-delete case (`isForeignKeyViolation` or `DomainError` `not_found`) is dropped quietly at `logger.debug` — mirroring the existing `settleRunIfPresent` guard and the repo idiom of tracing expected races at debug; any other failure is logged at `logger.error`. The append stays best-effort, so the Run settles normally.
- Added `src/reliability/process-safety-net.ts` — `installProcessSafetyNet()` registers a `process.on('unhandledRejection')` handler that logs a legible error (with `runId`/`taskId` when the thrown value carries them) instead of being fatal. Wired into `main()` in `src/cli.ts`; the `harmonic start` respawn re-executes `cli.ts`, so both direct `serve` and the backgrounded child install the net. Scoped to `unhandledRejection` only — `uncaughtException` is deliberately left alone (resuming after a synchronous crash is unsafe and out of scope).

**Tests** — new `tests/runner-append-run-gone.test.ts`:
- reproduces the delete-during-append race (delete the run, then fire `recordRunEvent`) and asserts the promise settles with no error logged and nothing streamed — verified to fail without the fix (`recordRunEvent is not a function`);
- happy-path append still persists + streams;
- `logUnhandledRejection` logs a legible error carrying Run/Task context, and omits context for a non-Error reason.

**Verification** — `npm run typecheck` clean; `oxlint` clean on changed files; full suite `2372 passed, 1 failed`, the one failure being the pre-existing flaky event-loop-lag timing assertion in `tests/stats-async-path.test.ts` (unrelated to this change; passes in isolation).

**Acceptance criteria**
- [x] A task deleted mid-append does not crash the server; the failure is logged and the Run settles normally.
- [x] An unhandled rejection anywhere in the server is logged as a legible error (with Run/Task context where available) instead of being fatal.
- [x] Regression test reproduces the delete-during-append race and asserts survival.

**Comment by mintopia** [comment]
Resolved on branch `harmonic/task-375-run-1` (commit `eb438d3`).

## What changed

**AC1 — delete-during-append no longer crashes the server.** The fire-and-forget run-event append in `Runner.driveOnce` had a `.then()` with no `.catch()`. Extracted it into a private `recordRunEvent` (`src/execution/runner.ts`) that contains the rejection: a racing task-delete cascade removes the Run row mid-turn, so the append FK-violates — that run-gone race now logs at `debug` and the Run settles normally; any other failure logs at `error`. Neither is fatal. The FK discriminator reuses the existing `isForeignKeyViolation` helper (same guard used at `runner.ts:1020`).

**AC2 — process-level safety net.** New `src/reliability/process-safety-net.ts` installs an `unhandledRejection` handler that logs the rejection as a legible error — extracting Run/Task context when the rejected value carries `taskId`/`runId` — instead of letting Node make it fatal. It only listens for `unhandledRejection` (never swallows `uncaughtException`), and is wired once in the `serve` path in `src/cli.ts`. Any future fire-and-forget miss degrades to a logged event rather than a crash.

**AC3 — regression + unit tests.** `tests/runner-append-delete-race.test.ts` reproduces the race: create a task + run, delete the task (cascading the Run + run_events away), fire the append, and assert no `unhandledRejection` escapes and no run is resurrected. `tests/reliability-process-safety-net.test.ts` covers the backstop's context extraction and install/uninstall.

## Verification

- `npm run typecheck`: clean.
- New tests + neighbouring `runner-cancel-run-gone` pass.
- Full suite: 2371 passed. Three failures were in `tests/execution.test.ts` and `tests/stats-async-path.test.ts` (waitFor timeouts / event-loop-stall timing) under the CPU saturation of the parallel run — both files pass 33/33 when re-run in isolation, and neither touches the changed paths.
- Code-reviewed (separate agent): confirmed the `.catch()` is chained synchronously so no rejection escapes, the discriminator is correct, and only `unhandledRejection` is handled.

**Comment by mintopia** [comment]
Completed and merged by Harmonic (task 375).
